version: '3.8'

services:
  backend:
    build:
      context: ./devport-backend
    container_name: devport-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: devport-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: devport-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
